CREATE TABLE IF NOT EXISTS caldav_connections (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  display_name TEXT NOT NULL,
  base_url TEXT NOT NULL,
  username TEXT NOT NULL,
  password_encrypted TEXT NOT NULL,
  sync_enabled INTEGER NOT NULL DEFAULT 0,
  sync_direction TEXT NOT NULL DEFAULT 'pull',
  sync_events INTEGER NOT NULL DEFAULT 1,
  sync_tasks INTEGER NOT NULL DEFAULT 0,
  sync_interval_minutes INTEGER NOT NULL DEFAULT 60,
  sync_window_past_days INTEGER NOT NULL DEFAULT 30,
  sync_window_future_days INTEGER NOT NULL DEFAULT 365,
  last_test_at TEXT,
  last_test_status TEXT,
  last_test_message TEXT,
  last_sync_at TEXT,
  last_sync_status TEXT,
  last_sync_message TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(user_id)
);
